### ISSUE TITLE
[REMOVE] const femaleFirstNames

### ISSUE THREAD

**Issue by KingFruit85** [KingFruit85/DND-Randomised-Character-Creator-Refactor#12]
No longer used in core.js

**Comment by HedgehogHolly** [comment]
I removed femaleFirstNames from names.js but I did a search and it is still being used in core.js and futher down in names.js?

<img width="418" alt="1" src="https://user-images.githubusercontent.com/41140803/66575427-cde7e480-eb6d-11e9-8f86-f6323f920da0.png">
<img width="357" alt="2" src="https://user-images.githubusercontent.com/41140803/66575477-e22be180-eb6d-11e9-95e9-94103655b763.png">

**Comment by KingFruit85** [comment]
@HedgehogHolly 

I'm sure I updated and combined this ticket into #13 I'm not sure how you assigned this one as I thought it was closed/deleted. I don't see it on the project board 👀

To answer your questions, **both the functions in core.js can be removed.** as per #13 👍

The returnRandomName() function in name.js is the new name generation fuction that needs to be built out as per #24 . 

The arrays used in that function (femaleFirstNames & others) are array variables local to the names.js file(confusing duplication for now!).

If they were refering to the arrays in core.js, name.js would have to hold a refrence to that file. 

**Such reference would be declared at the top of the page like:**

`const core =require('./core.js);`

Declaring an reference like that would allow me to access variables and functions in core.js by adding the 'core' prefix to the statement, like:

`return utils.returnRandomArrayItem(core.femaleFirstNames);`

But we dont need to do that now because the function and the arrays are in the same file 😁
 
Pretty confusing at this point, but once the old stuff is deleted from core.js should be less confusing! 

hopefully that makes some sence?

**Comment by KingFruit85** [comment]
ahh I think this ticket was created on the first project board I created (Which I have since deleted)

I clearly don't understand how this all works 🤷‍♂️ , probably best to pick up #13 instead.

**Comment by HedgehogHolly** [comment]
Okie dokie! #13 it is 😄

**Comment by KingFruit85** [comment]
@HedgehogHolly Apreciate it!
