### ISSUE TITLE
[ADD] Calculate AC

### ISSUE THREAD

**Issue by KingFruit85** [KingFruit85/DND-Randomised-Character-Creator-Refactor#2]
Take into account class features, armor & protental feats

**Comment by KingFruit85** [comment]
```
function calculateArmorClass(character){

  let ac = 10;

  if(character.characterClass.equipment.armor === undefined){
    ac += character.abilityScores.dexMod;
    return ac;
  }else{
    ac = character.characterClass.equipment.armor.baseArmorClass;
    ac += character.abilityScores.dexMod;
  }
  return ac;
}
```


Something like that ^^

Should probably take into account feats (when variant human is implemented) and class abilities like unarmoured defence etc

**Comment by Cadesh** [comment]
Hi @KingFruit85 I can work on this. 
Also if you like I can add some JEST tests to test the function to calculate AC.

**Comment by Cadesh** [comment]
It will be something like you proposed above:
- if armor
-- add base armor
-- check dex limits for armor type
          --- add dex
- no armor
   -- add dex
   -- check/add different professions bonus._
