### ISSUE TITLE
[UPDATE] returnRandomName()

### ISSUE THREAD

**Issue by KingFruit85** [KingFruit85/DND-Randomised-Character-Creator-Refactor#24]
In names.js

expand returnRandomName() to return a name suitable for the race/gender supplied as an arguement.

**Comment by Cadesh** [comment]
@KingFruit85, can I work on this issue?

**Comment by KingFruit85** [comment]
@Cadesh

Of course :) 

Let me know if you need any further info to get going

**Comment by KingFruit85** [comment]
@HedgehogHolly 

### before you start
You'll find it easier if you rename the current maleFirstNames & femaleFirstnames arrays to something like maleHumanNames / femaleHumanNames to avoid confusion and to fit in with the current theme.

So while there are probably may ways to accomplish this task I'm going to briefly describe what I think the two simplest ways are.

### if/else if loop

So this would just be and extension of the current function, you would need to add extra conditionals to capture all the possible race/gender combinations, below I have expanded the function to test for both gender and race in the if condition and also added dwarf name combinations:

```
function returnRandomName(character){

  if(character.gender === "male" && character.race === "human"){
    character.firstName = utils.returnRandomArrayItem(maleHumanNames);
    character.lastName = utils.returnRandomArrayItem(humanLastNames);
  }
  else if(character.gender === "male" && character.race === "human"){
    character.firstName = utils.returnRandomArrayItem(femaleHumanNames);
    character.lastName = utils.returnRandomArrayItem(humanLastNames);
  }
  else if(character.gender === "male" && character.race === "dwarf"){
    character.firstName = utils.returnRandomArrayItem(maleDwarfNames);
    character.lastName = utils.returnRandomArrayItem(dwarfSurnames);
  }
  else if(character.gender === "female" && character.race === "dwarf"){
    character.firstName = utils.returnRandomArrayItem(femaleDwarfNames);
    character.lastName = utils.returnRandomArrayItem(dwarfSurnames);
  }
  return character;
}
```
So this is one approach, and probably the most common and it should be fairly clear how to expand it to meet the task requirements.

That being said, it's not particularly elegant (in my opinion!)

### switch statements

personally I prefer switch statements to big if/else loops, it's pretty much the same concept, you provide an expression and if that expression is covered in the function then it executes some code. 

so, basic switch case statement looks like this:

```
switch (expression) {
  case expression1: //code here that executes if this expression matches the above expression
    break;
  case expression2://if the first isnt a match, try this one
    break;
  case expression3://and so on
    break;
  case expression4://and so on...
    break;
  default://If nothing matches execute code placed here 
}
```

an example with some values in it:
```

function whatColourIsHollysHairThisWeek(colour){//colour could be any string we pass the function

  switch (true) {
    case colour === "blonde": console.log("Holly's hair is blonde!"); //if the arguement we pass into the function is blone, this code gets executed 
      break;//the break makes sure the switch statement doesnt continue evaluating the other cases
    case colour === "red": console.log("Holly's hair is red!");
      break;
    case colour === "ginger": console.log("Holly's hair is ginger!");
      break;
    case colour === "blue": console.log("Holly's hair is blue!");
      break;
    default:console.log("Oh, haven't seen that one before!!");//if the arguement we pass doesnt match any of the cases, execute this
      
  }
}
```
So what do you think, is that enough to go on?

I have tried to to give you the full answer, and you should be able to look other switch cases in the code to see how to format multi conditional lines.

**Comment by HedgehogHolly** [comment]
How does this look? (I know the tabbing is wrong)

```
function returnRandomName(character){
  switch (true) {
    case character.race === "dwarf" && character.gender === "male":  
    character.firstName = utils.returnRandomArrayItem(maleDwarfNames);
    character.lastName = utils.returnRandomArrayItem(dwarfSurnames);
    break;
    case character.race === "dwarf" && character.gender === "female":  
    character.firstName = utils.returnRandomArrayItem(femaleDwarfNames);
    character.lastName = utils.returnRandomArrayItem(dwarfSurnames);
  }
}

**Comment by HedgehogHolly** [comment]
This also doesn't work 

```

function returnRandomName(character){
  switch (true) {
    case character.race === "dwarf" && character.gender === "male":  
    character.firstName = utils.returnRandomArrayItem(maleDwarfNames);
    character.lastName = utils.returnRandomArrayItem(dwarfSurnames);
    return character;

    case character.race === "dwarf" && character.gender === "female":  
    character.firstName = utils.returnRandomArrayItem(femaleDwarfNames);
    character.lastName = utils.returnRandomArrayItem(dwarfSurnames);
    return character;
  }

```
Am I returning the wrong thing?  I also read that the return means you don't need the break as well

**Comment by KingFruit85** [comment]
Try losing the return after your code blocks and move it to the last curly brace pair. Also add the breaks back in.

```
function returnRandomName(character){
  switch (true) {
    case character.race === "dwarf" && character.gender === "male":  
    character.firstName = utils.returnRandomArrayItem(maleDwarfNames);
    character.lastName = utils.returnRandomArrayItem(dwarfSurnames);
    break;

    case character.race === "dwarf" && character.gender === "female":  
    character.firstName = utils.returnRandomArrayItem(femaleDwarfNames);
    character.lastName = utils.returnRandomArrayItem(dwarfSurnames);
    break;
  }
  return character;
}
```

So the point about not needing the return is correct, but i think it's valid **if the code we execute is only a return statement**.

    `case character.race === "dwarf" && character.gender === "male":  return "my name is jeff";`

I'm still learning as I go so that could be totally wrong, but it's been my experience so far

**Comment by HedgehogHolly** [comment]
It still comes up as undefined, Ive tried your code and with it as (character) "character" but none seem to be working.  

I'll keep messing around

**Comment by KingFruit85** [comment]
do you have a default statement in there? I normally set my default to a string like "fell though switch case"

**Comment by KingFruit85** [comment]
Oh! pretty sure the races are capitalized.

So it should be 

`case character.race === "Dwarf" && character.gender === "male": `

**Comment by KingFruit85** [comment]
I'll have to rectify that, everything should be lowercase 🤦‍♂️

**Comment by KingFruit85** [comment]
Ok so just had a look and figured it out.

Without spoiling it, the problem isn't your switch case, provided it looks something like this:

```
function returnRandomName(character){
  switch (true) {
    case character.race === "Dwarf" && character.gender === "male":
    character.firstName = utils.returnRandomArrayItem(maleDwarfNames);
    character.lastName = utils.returnRandomArrayItem(dwarfSurnames);
    break;

    case character.race === "Dwarf" && character.gender === "female":
    character.firstName = utils.returnRandomArrayItem(femaleDwarfNames);
    character.lastName = utils.returnRandomArrayItem(dwarfSurnames);
    break;
    default:character.firstName = "well"; character.lastName = "shit";
  }

  return character;
}
```

The problem is actually located in core.js and involves the order in which the character object is created in NewCharacter().

I'll leave you with that, and if it still doesn't make sense let me know.
