### ISSUE TITLE
[IMPROVE] Alphabetise Names and Add Sections

### ISSUE THREAD

**Issue by HedgehogHolly** [KingFruit85/DND-Randomised-Character-Creator-Refactor#31]
To make the names file easier to read it might be good to put them in alphabetical order by race and add a comment to separate sections e.g:

#### /*  DWARF  */
femaleDwarfNames
maleDwarfNames
dwarfSurnames

#### /*  HUMAN  */
femaleHumanNames
maleHumanNames
humanSurnames

#### /*  TIEFLING  */
femaleTieflingNames
maleTieflingNames
TieflingSurnames

**Comment by KingFruit85** [comment]
Sounds like a fair idea 🧙‍♂️
