### ISSUE TITLE
[BUG] Characters getting armor they don't have the strength to wear

### ISSUE THREAD

**Issue by KingFruit85** [KingFruit85/DND-Randomised-Character-Creator-Refactor#32]
add STR check before adding heavy armors, if not able to meet STR requirement assign the highest AC armor they are able to wear.

**Comment by HedgehogHolly** [comment]
Do you already have a function for determining armor to improve on? or do you need create one from scratch?

**Comment by KingFruit85** [comment]
@HedgehogHolly Hey, so character equipment is assigned in classes.js. 

Each class has a function such as:
```
----------
classes.js
----------
createBard()
createCleric()
etc...
```

Logic will have to be built in to these functions to check the characters strength score is high enough to wear the armor they have been assigned.

An if-loop should surfice to cover this. Also it should be worth noting that only some heavy armors have this requirement:

![image](https://user-images.githubusercontent.com/36999273/66638224-73519580-ec0c-11e9-84a9-e4e0e15c5166.png)

A change will also have to be made to the calling function in core.js 

```
----------
core.js
----------
returnRandomCharacterClass()
```

This will have to pass the characters strength score as an arguement so the class function in classes.js knows what value to check.


Happy to advise if you decide to pick it up 😁

**Comment by HedgehogHolly** [comment]
Yeah Im not sure where to start on this one 😅

**Comment by KingFruit85** [comment]
You might be right, It's a lot to pick up for your first function, I think a better starting point would be #24 . Much more straight forward.

EDIT: actually it's pretty much the same lol

**Comment by KingFruit85** [comment]
#
