### ISSUE TITLE
[IMPROVE] Create a pull request template

### ISSUE THREAD

**Issue by HedgehogHolly** [KingFruit85/DND-Randomised-Character-Creator-Refactor#38]
You can create a pull request template that makes it easier to describe fixes and you can connect it the issue you are working on and it.

[Tutorial](https://help.github.com/en/articles/manually-creating-a-single-issue-template-for-your-repository)
[Example](https://github.com/neontribe/contemplating-action/blob/1.0/release/.github/PULL_REQUEST_TEMPLATE.md)

It can also automatically close the issue if you list that it has solved the problem in the pull request [Github Docs](https://help.github.com/en/articles/closing-issues-using-keywords)

**Comment by KingFruit85** [comment]
@HedgehogHolly I think this is completed?

**Comment by HedgehogHolly** [comment]
Yep this is all done :)
