### ISSUE TITLE
[UPDATE] Add remaining feats

### ISSUE THREAD

**Issue by KingFruit85** [KingFruit85/DND-Randomised-Character-Creator-Refactor#41]
Only for variant humans at this point but nice to have if we implement leveling

**Comment by HedgehogHolly** [comment]
Is that adding the rest of these [feats](https://www.aidedd.org/dnd-filters/feats.php) and their effects to feats.js file? If so I can probably do most of them, unless they have a really weird effect

**Comment by KingFruit85** [comment]
I double checked the 5e SRD and I think they only include the grappler feat, so I think for legal reasons we should probably avoid adding any official content.

I'll double check what I have already implemented late and update

**Comment by HedgehogHolly** [comment]
Does that mean we can literally only add the grappler feat and nothing else?

**Comment by KingFruit85** [comment]
Yep! see: https://www.5esrd.com/feats/

Going to close this down for now
