### ISSUE TITLE
[ADD] Additional Half-Elf names

### ISSUE THREAD

**Issue by KingFruit85** [KingFruit85/DND-Randomised-Character-Creator-Refactor#5]
Add additional first names and surnames to names.js

**Because halfelves can have a mixture of human/elf parents, perhaps adding the option for a half elf to have a human first name, elven surname or visa versa would be cool**

names can be generated from several online fantasy generators 

I know it's simple but good for a total beginner learning forking, cloning & pull requests.

**Comment by cindyledev** [comment]
Hello, may I contribute to this?

**Comment by KingFruit85** [comment]
Added code that merges the human and half-elf name arrays together before picking a random value.

Just need to add a bunch more half elf options

**Comment by KingFruit85** [comment]
Added:
 100 male half-elf names
 100 female half-elf names
 200 half-elf surnames
