### ISSUE TITLE
[ADD] character physical attributes

### ISSUE THREAD

**Issue by KingFruit85** [KingFruit85/DND-Randomised-Character-Creator-Refactor#56]
Such as eye/hair colour, build. stuff like that

**Comment by HedgehogHolly** [comment]
Again, is this in its own js file?

**Comment by KingFruit85** [comment]
So I was thinking of ending up with an object variable along the lines of:

```
physicalAttributes:{
  hairColour:"";
  hairLength:"";
  hairStyle:";
  eyeColour:"";
  eyeSize:"";
  skinColour:"";
  armLength:"";
  legLength:"";
  posture:"";
  gait:"";
}
```

Might be fun to go crazy with details, generate some crazy looking dudes!

Will probably make sense to fold the height/weight functions into this as well, assuming a new file is created, but that can be further down the line.

**Comment by KingFruit85** [comment]
I have set up a basic function/collections to do this PhysicalAttributes()

I'll expand at a later date
