### ISSUE TITLE
[ADD] Ideals, bonds, flaws

### ISSUE THREAD

**Issue by KingFruit85** [KingFruit85/DND-Randomised-Character-Creator-Refactor#57]
A list of SRD compliant data can be found [here ](https://www.5esrd.com/backgrounds/)

**Comment by HedgehogHolly** [comment]
Where would this be added to? or would it be in its own js file?  and are you ignoring Personality trait?

**Comment by KingFruit85** [comment]
I think it would be appropriate for this to have its own file, maybe the physical attributes can be folded into this as well

**Comment by HedgehogHolly** [comment]
```
const bond = {
    one: {
        description: "I would die to recover an ancient relic of my faith that was lost long ago."
    },
    two: {
        description: "I will someday get revenge on the corrupt temple hierarchy who branded me a heretic."
    },
    three: {
        description: "I owe my life to the priest who took me in when my parents died."
    },
    four: {
        description: "Everything I do is for the common people."
    },
    five: {
        description: "I will do anything to protect the temple where I served."
    },
    six: {
        description: "	I seek to preserve a sacred text that my enemies consider heretical and seek to destroy"
    },
},

Is this even remotely close?

**Comment by KingFruit85** [comment]
Yep! So I would make collections for the others, then a function to pull a random item from each collection and return them

**Comment by KingFruit85** [comment]
@HedgehogHolly 
OK so I have taken a look over the code snippets you have sent me and it looks pretty good, just a couple of small things that are probably holding you up!

I'm going to be annoyingly vague so you can do a bit of investigating but if it would be more helpful for me just to tell you want to do just say 👍

So what you have linked above is a object who's properties are other objects, and that's certainly one way to approach this task. However my advice for sort of thing is to try and use an _array_ of strings (not _objects_ within an _object_). But if you wanted to stick with your approach, i made a function in utils.js called returnRandomObjectPropertiesAndValues() that should do what you want.

**Arrays:**
An array of stings is defined like this 

`const vegetables = ['Carrot', 'Potato', 'Turnip'];`

Notice the square brackets, and array can hold pretty much any data type afaik, like:

An array of objects:

```
const vegetables = [
  (Carrot = { name: "carrot", colour: "orange" }),
  (Potato = { name: "potato", colour: "white" }),
  (Turnip = { name: "turnip", colour: "off-white" })
];
```

Next, your function

```
function returnRandomPersonality(personality) {
    personalityTrait = {
        personality: utils.returnRandomArrayItem(personality)
    };


    return personality;
    
}
```

So we don't need an argument here assuming the call to this function looks something like this?

`this.personalityTraits = returnRandomPersonality();`

What we want this function to do is return an object containing one ideal one bond, one flaw & one personality trait right?

So first we would need collections strings/objects for each of those, and then the function would grab one of each, assign it to it's own internal collection and return that. So what I think the end result you're going for is a character object with the following(it's in JSON format but you should get the idea...):


```
{
  "level": 1,
  "proficiencyModifier": 2,
  "characterClass": {
    "name": "bard",
    "primaryAbility": "cha",
    "castingAbility": "cha",
    "hitDie": 8,
    "savingThrows": [
      "dex",
      "cha"
    ],
    "personalityTraits": {
      "ideal":"this is my ideal!",
      "bond":"this is my bond!",
      "flaw":"This is my flaw!",
      "Personality Trait":"This is my Personality"
    },
    "armorProficiencies": [
      "light armor"
    ],
```
Is that enough to go on?
