### ISSUE TITLE
[ADD] Additional Halfling names

### ISSUE THREAD

**Issue by KingFruit85** [KingFruit85/DND-Randomised-Character-Creator-Refactor#6]
Add additional first names and surnames to names.js

names can be generated from several online fantasy generators 

I know it's simple but good for a total beginner learning forking, cloning & pull requests.

**Comment by cindyorangis** [comment]
Hello, can I contribute to this?

**Comment by KingFruit85** [comment]
@cindyledev Of course, see pull request for feddback 😁
